apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: {{ .Values.myApp.replicas }}
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: {{ .Values.myApp.image }}
        imagePullPolicy: Never
        ports:
        - containerPort: {{ .Values.myApp.containerPort }}
