apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: {{ .Values.myapp.containerPort }}
    targetPort: {{ .Values.myapp.containerPort }}
    nodePort: {{ .Values.myapp.nodePort }}
