apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  sources:
    - helm:
        valueFiles:
          - values.yaml
      path: helmChart/apps
      repoURL: https://github.com/shimaaaa/python_k8s_algocd.git
      targetRevision: main
